image: node:8

stages:
  - prepare
  - test
  - build
  - deploy

cache:
  key: '$CI_COMMIT_REF_SLUG'
  paths:
    - node_modules/

.job_template: &aws-setup
  before_script:
    - apt-get update -qq
    - apt-get install -qy libelf1
    - apt-get install -qy python-pip python-dev
    - pip install --user awscli
    - mkdir .aws
    - echo '[default]' > .aws/credentials
    - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> .aws/credentials
    - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> .aws/credentials

.notify:
  before_script:
    - curl -X POST -H "Content-type:\ application/json" --data "{\"text\":\"*DEPLOYMENT ALERT* \` $CI_PROJECT_NAME > $CI_COMMIT_REF_NAME \` ($CI_ENVIRONMENT_URL) \n\n $CI_COMMIT_MESSAGE \n _ CI/CD Job $CI_PIPELINE_URL _ \n _*Deployment triggered by $GITLAB_USER_NAME*_ \"}" https://hooks.slack.com/services/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

.notify_after:
  after_script:
    - curl -X POST -H "Content-type:\ application/json" --data "{\"text\":\"*DEPLOYMENT:* \` $CI_PROJECT_NAME > $CI_COMMIT_REF_NAME \` ($CI_ENVIRONMENT_URL) *DONE*\"}" https://hooks.slack.com/services/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

setup:
  stage: prepare
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

legacy-landing-page::build:prod:
  stage: build
  extends: .notify
  environment:
    name: www.truck-jobs.de Prod
    url: www.truck-jobs.de
  script:
    - yarn install
    - yarn run build:libs
    - cd packages/legacy-landing-page/; yarn run build:prod;
  artifacts:
    paths:
      - packages/legacy-landing-page/build/
  only:
    - landing-page-prod

legacy-landing-page::build:stage:
  stage: build
  script:
    - yarn install
    - yarn run build:libs
    - cd packages/legacy-landing-page/; yarn run build:stage;
  artifacts:
    paths:
      - packages/legacy-landing-page/build/

publish-prod:
  stage: deploy
  extends: .notify_after
  <<: *aws-setup
  environment:
    name: www.truck-jobs.de Prod
    url: www.truck-jobs.de
  only:
    - landing-page-prod
  script:
    - ~/.local/bin/aws s3 sync packages/legacy-landing-page/build/ s3://landing-page.truck-jobs.de/ --cache-control max-age=31536000
    - ~/.local/bin/aws s3 cp packages/legacy-landing-page/includes/sitemap.xml s3://landing-page.truck-jobs.de/ --cache-control max-age=3600
    - ~/.local/bin/aws s3 cp packages/legacy-landing-page/includes/robots.txt s3://landing-page.truck-jobs.de/ --cache-control max-age=3600
    - for fl in $(~/.local/bin/aws s3 ls  landing-page.truck-jobs.de/ --recursive | grep "\.html" | sed -e 's/^[-0-9]\{10\} [\:0-9]\{8\} * [0-9]* //');do ~/.local/bin/aws s3 mv --content-type="text/html" s3://landing-page.truck-jobs.de/$fl s3://landing-page.truck-jobs.de/${fl/\.html/};done
    - ~/.local/bin/aws s3api put-object --acl public-read --website-redirect-location '/' --bucket landing-page.truck-jobs.de --key 'drivers/index.html'
    - ~/.local/bin/aws s3api put-object --acl public-read --website-redirect-location '/fahrer/jobsuche' --bucket landing-page.truck-jobs.de --key 'driver/profile/licenses'
    - ~/.local/bin/aws s3api put-object --acl public-read --website-redirect-location '/impressum' --bucket landing-page.truck-jobs.de --key 'infos/jobsuche/impressum'
    - ~/.local/bin/aws s3api put-object --acl public-read --website-redirect-location '/nutzungsbedingungen' --bucket landing-page.truck-jobs.de --key 'infos/jobsuche/nutzungsbedingungen'
    - ~/.local/bin/aws s3api put-object --acl public-read --website-redirect-location '/datenschutz' --bucket landing-page.truck-jobs.de --key 'infos/jobsuche/datenschutz'
    - ~/.local/bin/aws cloudfront create-invalidation --distribution-id ETY6523Z6A6AS --paths "/*"
  dependencies:
    - legacy-landing-page::build:prod

publish-stage:
  stage: deploy
  <<: *aws-setup
  environment:
    name: stage
  script:
    - ~/.local/bin/aws s3 sync packages/legacy-landing-page/build/ s3://stage.landing-page.truck-jobs.de/ --cache-control max-age=31536000
    - ~/.local/bin/aws s3 cp packages/legacy-landing-page/includes/robots.txt s3://stage.landing-page.truck-jobs.de/ --cache-control max-age=3600
    - for fl in $(~/.local/bin/aws s3 ls  stage.landing-page.truck-jobs.de/ --recursive | grep "\.html" | sed -e 's/^[-0-9]\{10\} [\:0-9]\{8\} * [0-9]* //');do ~/.local/bin/aws s3 mv --content-type="text/html" s3://stage.landing-page.truck-jobs.de/$fl s3://stage.landing-page.truck-jobs.de/${fl/\.html/};done
    - ~/.local/bin/aws cloudfront create-invalidation --distribution-id E8B3M999LMHF2 --paths "/*"
  dependencies:
    - legacy-landing-page::build:stage
